Update pipeline to install required SDK version (#41)
* try to install exact sdk with error check and validation
* bump minor version

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -8,20 +8,49 @@ trigger:
     - src/OAKProxy
 
 jobs:
-- job: build_win
-  displayName: Build Windows
+- job: get_sdk_version
+  displayName: Determine SDK Version
   pool:
-    vmImage: vs2017-win2016
+    vmImage: ubuntu-16.04
   steps:
   - checkout: self
     clean: all
     fetchDepth: 1
+  - script: |
+      version=$(cat global.json | jq -r '.sdk.version')
+      if [[ -z $version ]]; then
+        echo "Failed to get SDK version"
+        exit 1
+      fi
+      echo "SDK Version from global.json is $version"
+      echo "##vso[task.setvariable variable=dotnetSdkVersion;isOutput=true]$version"
+    name: parse
+    workingDirectory: src/OAKProxy
+    displayName: Parse Version
+- job: build_win
+  dependsOn: get_sdk_version
+  displayName: Build Windows
+  pool:
+    vmImage: vs2017-win2016
+  variables:
+    dotnetSdkVersion: $[ dependencies.get_sdk_version.outputs['parse.dotnetSdkVersion'] ]
+  steps:
+  - checkout: self
+    clean: all
+    fetchDepth: 1
+  - task: UseDotNet@2
+    displayName: 'Use .NET Core SDK'
+    inputs:
+      packageType: sdk
+      version: $(dotnetSdkVersion)
   - task: NuGetCommand@2
     displayName: 'Add Azure DevOps Artifacts Credential'
     inputs:
       command: custom
       arguments: sources update -Name corefx-s4u -Username vsts -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile src/OAKProxy/Nuget.Config
-  - script: dotnet publish -c Release -f netcoreapp2.2 -r win-x64 --self-contained true
+  - script: |
+      dotnet --version
+      dotnet publish -c Release -f netcoreapp2.2 -r win-x64 --self-contained true
     workingDirectory: src/OAKProxy
     displayName: Build
   - task: PublishPipelineArtifact@0
@@ -29,19 +58,29 @@ jobs:
       artifactName: oakproxy-windows
       targetPath: src/OAKProxy/bin/Release/netcoreapp2.2/win-x64/publish
 - job: build_linux
+  dependsOn: get_sdk_version
   displayName: Build Linux
   pool:
     vmImage: ubuntu-16.04
+  variables:
+    dotnetSdkVersion: $[ dependencies.get_sdk_version.outputs['parse.dotnetSdkVersion'] ]
   steps:
   - checkout: self
     clean: all
     fetchDepth: 1
+  - task: UseDotNet@2
+    displayName: 'Use .NET Core SDK'
+    inputs:
+      packageType: sdk
+      version: $(dotnetSdkVersion)
   - task: NuGetCommand@2
     displayName: 'Remove DevOps Artifacts Source'
     inputs:
       command: custom
       arguments: sources remove -Name corefx-s4u -ConfigFile src/OAKProxy/NuGet.Config
-  - script: dotnet publish -c Release -f netcoreapp2.2 -r linux-x64 --self-contained false
+  - script: |
+      dotnet --version
+      dotnet publish -c Release -f netcoreapp2.2 -r linux-x64 --self-contained false
     workingDirectory: src/OAKProxy
     displayName: Build
   - task: PublishPipelineArtifact@0
